import type { Metadata } from "next";
import React from "react";
import "./globals.css";
import { ThemeProvider } from "./ThemeContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type NavButton = {
  name: string;
  href: string;
}

const navbarItemStyles = "bg-gradient-to-r from-purple-500 to-pink-500"
const navButtons: NavButton[] = [
  {
    name: "Home",
    href: "/",
  },
  {
    name: "About",
    href: "/",
  },
  {
    name: "Projects",
    href: "/",
  },
  {
    name: "Contact",
    href: "/",
  }
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body className={`antialiased`}>
          <div className="w-screen p-10 flex border-b-8 items-center">
            <div className={`${navbarItemStyles} bg-clip-text text-transparent`}>
              <p className="text-3xl font-bold">anahadh.multani.dev</p>
            </div>

            <nav className="relative flex p-5 text-purple gap-x-10 ml-auto items-center">
              {navButtons.map((button) => {
                return <div className="relative group" key={button.name}>
                  <a href={button.href} key={button.name} className="text-2xl font-black relative z-0">
                    {button.name}
                  </a>
                  <div className={`absolute bottom-[-5] left-0 w-full h-1 ${navbarItemStyles} transform w-0 group-hover:w-full transition-all duration-300 ease-in-out`}></div>
                </div>
              })}
            </nav>
          </div>
          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
