import type { Metadata } from "next";
import React from "react";
import "./globals.css";
import { ThemeProvider } from "../contexts/ThemeContext";
import { WebsiteLogo } from "../components/WebsiteLogo";
import { Navbar } from "../components/Navbar";
import { Arvo, Noto_Sans } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const arvo = Arvo({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-arvo",
});

const notoSans = Noto_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-noto-sans",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body className={`${arvo.variable} ${notoSans.variable}`} cz-shortcut-listen="true">
          <div className="w-screen p-10 flex border-b-8 items-center">
            <WebsiteLogo />
            <Navbar />
          </div>
          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
